version: '3.8'

services:
  db:
    restart: always
    image: neo4j:4.4-community
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/password
    volumes:
      - data:/data
      - logs:/logs
  web:
    build: .
    ports:
      - "8000:80"
    env_file:
      - .env
    depends_on:
      - db
volumes:
  data:
  logs:
