site_name: Onyx Salamander Headless CMS
site_url: http://onyx-salamander-headless-cms.readthedocs.io/
nav:
  - Home: index.md
  - About: about.md
  - Quickstart: quickstart.md
  - User Guide: user/index.md
  - Developer Guide: dev/index.md
theme: readthedocs